USE Exelot_BI_Project

--DROP TABLE COUNTRIES
--TRUNCATE TABLE COUNTRIES
CREATE TABLE COUNTRIES (
	Country		VARCHAR(20)	NOT NULL,
	Continent	VARCHAR(20),
	Population	INTEGER,
	CONSTRAINT PK_COUNTRIES PRIMARY KEY (Country)
	)

--DROP TABLE SITES
--TRUNCATE TABLE SITES
CREATE TABLE SITES (
	ID					INTEGER		NOT NULL,
	Name				VARCHAR(20),
	[Contract Date]		DATE,
	Fee					MONEY,
	Country				VARCHAR(20),
	CONSTRAINT PK_SITES PRIMARY KEY (ID),
	CONSTRAINT CK_FEE CHECK (Fee > 0),
	CONSTRAINT FK_SITES_TO_COUNTRIES FOREIGN KEY (Country)
		REFERENCES COUNTRIES (Country)
	)

--DROP TABLE IMPORTERS
--TRUNCATE TABLE IMPORTERS
CREATE TABLE IMPORTERS (
	ID			INTEGER		NOT NULL,
	Country		VARCHAR(20),
	Region		VARCHAR(20),
	City		VARCHAR(20),
	Birthdate	DATE,
	CONSTRAINT PK_IMPORTERS PRIMARY KEY (ID),
	CONSTRAINT FK_IMPORTERS_TO_COUNTRIES FOREIGN KEY (Country)
		REFERENCES COUNTRIES (Country)
	)

--DROP TABLE AIRWAY_BILLS
--TRUNCATE TABLE AIRWAY_BILLS
CREATE TABLE AIRWAY_BILLS (
	ID					INTEGER		NOT NULL,
	[From]				VARCHAR(20), 
	[To]				VARCHAR(20),
	[Sum Order Cost]	MONEY,
	ETA					DATE,
	ATA					DATE,
	CONSTRAINT PK_AIRWAY_BILLS PRIMARY KEY (ID),
	CONSTRAINT FK_AIRWAY_BILLS_TO_COUNTRIES1 FOREIGN KEY ([From])
		REFERENCES COUNTRIES (Country),
	CONSTRAINT FK_AIRWAY_BILLS_TO_COUNTRIES2 FOREIGN KEY ([To])
		REFERENCES COUNTRIES (Country)
	)

--DROP TABLE ORDERS
--TRUNCATE TABLE ORDERS
CREATE TABLE ORDERS (
	[DW ORDER]			INTEGER, --surrogate key for incremental loading
	OrderID				INTEGER		NOT NULL,
	[Site ID]			INTEGER		NOT NULL,
	[Importer ID]		INTEGER		NOT NULL,
	[Order Date]		DATE		NOT NULL,
	[Airway Bill ID]	INTEGER		NOT NULL,	
	[Delivery Method]	VARCHAR(20),
	[Order Cost]		MONEY,
	[Delivery Cost]		MONEY,
	[Sum Order Cost]	MONEY,
	ETA					DATE,
	ATA					DATE,
	Satisfaction		INTEGER,	
	CONSTRAINT PK_ORDERS PRIMARY KEY (OrderID, [Site ID]),
	CONSTRAINT FK_ORDER_TO_SITE FOREIGN KEY ([Site ID])
		REFERENCES SITES (ID),
	CONSTRAINT FK_ORDERS_TO_IMPORTERS FOREIGN KEY ([Importer ID])
		REFERENCES IMPORTERS (ID),
	CONSTRAINT FK_ORDERS_TO_AIRWAY_BILLS FOREIGN KEY ([Airway Bill ID])
		REFERENCES AIRWAY_BILLS (ID),
	CONSTRAINT CK_SATISFACTION CHECK (Satisfaction BETWEEN 1 AND 5)
	)

--DROP TABLE DISTRIBUTORS
--TRUNCATE TABLE DISTRIBUTORS
CREATE TABLE DISTRIBUTORS (
	ID						INTEGER		NOT NULL,
	Name					VARCHAR(20),
	[Max Parcels Per Day]	INTEGER,
	Handling				MONEY,
	[Start Date]			DATE,
	Score					INTEGER,
	CONSTRAINT PK_DISTRIBUTORS PRIMARY KEY (ID),
	CONSTRAINT CK_HANDLING CHECK (Handling > 0),
	CONSTRAINT CK_SCORE CHECK (Score BETWEEN 1 AND 5)
	)

--DROP TABLE PARCELS
--TRUNCATE TABLE PARCELS
CREATE TABLE PARCELS (
	ID					INTEGER		NOT NULL,
	OrderID				INTEGER		NOT NULL,
	[Site ID]			INTEGER		NOT NULL,
	Distributor			INTEGER		NOT NULL,
	[Customs Clearance]	BIT,
	Weight				FLOAT,
	[Delivery Date]		Date,
	CONSTRAINT PK_PARCELS PRIMARY KEY (ID),
	CONSTRAINT FK_PARCELS_TO_ORDERS FOREIGN KEY (OrderID, [Site ID])
		REFERENCES ORDERS (OrderID, [Site ID]),
	CONSTRAINT FK_PARCELS_TO_DISTRIBUTORS FOREIGN KEY (Distributor)
		REFERENCES DISTRIBUTORS (ID)
	)

--DROP TABLE SITE_RATES
--TRUNCATE TABLE SITE_RATES
CREATE TABLE SITE_RATES (
	[Site Rate ID]		INTEGER		NOT NULL,
	Year				INTEGER,
	Name				VARCHAR(20),
	Country				VARCHAR(20),
	[Average Rate]		FLOAT,
	[Num Of Rates]		INTEGER,
	[Orders Count]		INTEGER,
	CONSTRAINT PK_SITE_RATES PRIMARY KEY ([Site Rate ID], Year)
	)










